# configuration for https://github.com/caksoylar/keymap-drawer
parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans
  
  raw_binding_map:
    '&reset': Reset
    '&sys_reset': Reset
    '&bootloader': Boot
    '&SlAppy': Win Next
    '&SlApBack': Win Prev
    '&caps_word': Caps Wrd
    '&inv_qm': ¿
    
    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none
      
    '&out OUT_USB': Out USB
    '&out OUT_BLE': Out BLE

    # Bluetooth
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$

    '&mmv M_UP': M↑
    '&mmv M_DOWN': M↓
    '&mmv M_LEFT': M←
    '&mmv M_RIGHT': M→

    '&mwh S_UP': MW↑
    '&mwh S_DOWN': MW↓
    '&mwh S_LEFT': MW←
    '&mwh S_RIGHT': MW→

    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click

  zmk_combos:
    combo_tab:    {align: top, o: 0.15}
    combo_del:    {align: top, o: 0.15}
    combo_t_Coln: {align: top, o: 0.25}
    combo_appswitch:    {align: top}
    combo_btclr:  {align: bottom}
    combo_t_Q:    {align: top, o: 0.3}
    combo_t_Z:    {align: top}
    combo_t_V:    {align: bottom, o: 0.15}
    combo_docaps: {draw_separate: true}
    combo_capslk:   {draw_separate: true}
    combo_Gent:   {draw_separate: true}
    combo_entr:    {draw_separate: true}
    combo_spce: {draw_separate: true}
    combo_esc:   {draw_separate: true}
    combo_sall:   {draw_separate: true}
    combo_numpad:    {align: bottom, o: 0.15}
    combo_sch:   {draw_separate: true}
    combo_tch:   {draw_separate: true}

zmk_keycode_map:
     
   # Whitespace
    ESC: Esc
    SPACE: ␣
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$

    # custom mappings
    LC(LG(LEFT)): Desk Left
    LC(LG(RIGHT)): Desk Right
    LC(TAB): Tab Left
    LC(LS(TAB)): Tab Right
    LA(F4): Win Close
    LC(F4): Tab Close
    
    C_AL_CALC: Calc
    LS(INS): Paste

  
    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RGUI: $$mdi:apple-keyboard-command$$
    LS(LC(LALT)): $$mdi:triangle$$ # Meh

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$
 
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: .
    APOSTROPHE: <
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _
